server:
  port: 80
  servlet:
    context-path: /

spring:

  datasource:
    url: jdbc:h2:mem:test
    username: root
    password: 1234
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create

    properties:
      hibernate:
        format_sql: true # sql 예쁘게 출력
        default_batch_fetch_size: 1000
        show-sql: true

  jackson:
    property-naming-strategy: SNAKE_CASE

  logging:
    level:
      org.hibernate.type: trace # sql binding 값 출력

kakao:
  client:
    id: 661685b0f0b7c48454e26b4cd57f2db1
    secret: 3EbfiGsb9bam4fx3LhLKlDnSuM8PZ7Zx
    redirect-uri: http://localhost/api/auth/kakao/callback